FROM redis:3.2.10-alpine
MAINTAINER Lee <lonisy@163.com>

# https://redis.io/topics/config
# https://www.cnblogs.com/Fooo/p/6599100.html
# https://hub.docker.com/

# COPY redis.conf /usr/local/etc/redis/redis.conf
# ENTRYPOINT ["docker-entrypoint.sh"]

WORKDIR /data
VOLUME ["/data"]


